-- SQL Schema for BCA Fest 2026 Registration
-- Paste this script into your Supabase SQL Editor and execute it to create the table.

CREATE TABLE IF NOT EXISTS registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable row-level security (RLS) on the table (Optional/Recommended)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous insert (public submit form)
CREATE POLICY "Allow public insert to registrations" 
ON registrations FOR INSERT 
WITH CHECK (true);

-- Create policy to allow select registrations (Optional - for admin views)
CREATE POLICY "Allow public select from registrations" 
ON registrations FOR SELECT 
USING (true);
